# Generated by Django 4.2.7 on 2025-08-19 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('reference_id', models.CharField(help_text='Unique reference ID from payment provider', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (GCash, Maya, etc.)', max_length=50, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider', max_length=100, null=True)),
                ('callback_data', models.JSONField(blank=True, default=dict, help_text='Raw callback data from payment provider')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee charged', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after fees', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When transaction was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about transaction', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when transaction was created', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_tra_user_id_131e27_idx'), models.Index(fields=['reference_id'], name='payment_tra_referen_87720b_idx'), models.Index(fields=['transaction_type', 'status'], name='payment_tra_transac_0f64bd_idx'), models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx')],
            },
        ),
    ]
