# Generated by Django 4.2.7 on 2025-08-19 07:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('api_request', 'API Request'), ('api_response', 'API Response'), ('callback', 'Callback Received'), ('status_change', 'Status Change'), ('error', 'Error'), ('manual_action', 'Manual Action')], max_length=20)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional log data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Payment method code (gcash, maya, etc.)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('la2568_bank_code', models.CharField(help_text='Bank code for LA2568 API', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10)),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Fee percentage (0.02 = 2%)', max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed fee amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_deposits', models.BooleanField(default=True)),
                ('supports_withdrawals', models.BooleanField(default=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='provider_transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes and actions', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='api_request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data sent to LA2568 API'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='api_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Response from LA2568 API'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP when transaction was created', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When transaction was completed', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='la2568_order_id',
            field=models.CharField(blank=True, help_text='LA2568 returned order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='la2568_transaction_id',
            field=models.CharField(blank=True, help_text='LA2568 transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Direct payment URL from LA2568', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qr_code_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded QR code image', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='QR code image URL', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of API retry attempts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='callback_data',
            field=models.JSONField(blank=True, default=dict, help_text='Callback data from LA2568'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net amount after fees', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('paymaya', 'PayMaya'), ('manual', 'Manual')], default='gcash', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When transaction was processed by LA2568', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(help_text='Unique reference ID (order_id for LA2568)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['la2568_order_id'], name='payment_tra_la2568__21419c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method'], name='payment_tra_payment_45950f_idx'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered this log (for manual actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['transaction', 'log_type'], name='payment_log_transac_ce1043_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['created_at'], name='payment_log_created_7a2b3a_idx'),
        ),
    ]
