# Generated by Django 4.2.7 on 2025-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='daily_return_rate',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
