# Generated by Django 4.2.7 on 2025-08-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='non_withdrawable_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='withdrawable_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
