# Generated by Django 4.2.7 on 2025-08-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_userprofile_non_withdrawable_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcommission',
            name='commission_type',
            field=models.CharField(choices=[('registration', 'Registration Bonus'), ('investment', 'Investment Commission')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.investment'),
        ),
    ]
